In [9]:
import pandas as pd

df = pd.read_parquet('../data/outages_2015-2024_clean.parquet')
print("✅ Loaded successfully!")

✅ Loaded successfully!

In [10]:
print(df.shape)  # (rows, columns)

(28080576, 12)

In [11]:
df.head(15)

                                                                                            ActualGenerationOutput  \
DateTime   Fuel                      EICCode          Unit                     UnitID
2015-01-01 Biomass                   nan              BMHKW Piesteritz         E000114-001                     NaN
           Fossil Brown coal/Lignite 11WD2BUSD0000386 Buschhaus                E000119-001                     NaN
                                     11WD7AUEN5BFOFBM Fabrik Fortuna Nord      E000081-001                     NaN
                                     11WD7BOLL5BFRFBC Fabrik Frechen/Wachtberg E000082-001                     NaN
                                     11WD7BOLL5XBEFBQ Fabrik Berrenrath        E000080-001                     NaN
                                     11WD7FRIM2B--P-G Frimmersdorf P           E000005-012                     NaN
                                     11WD7FRIM2B--Q-D Frimmersdorf Q           E000005-013                     NaN
                                     11WD7LIES5B-WRKC Goldenberg GoWerk        E000083-001                     NaN
                                     11WD7NEUR1B--B-X Neurath B                E000077-002                     NaN
                                     11WD7NEUR1B--C-U Neurath C                E000077-003                     NaN
                                     11WD7NEUR1B--D-R Neurath D                E000077-004                     NaN
                                     11WD7NEUR1B--E-O Neurath E                E000077-005                     NaN
                                     11WD7NEUR1B--F-L Neurath F                E000077-006                     NaN
                                     11WD7NEUR1B--G-I Neurath G                E000077-007                     NaN
                                     11WD7NEUR2B--A-T Neurath A                E000077-001                     NaN

                                                                                            AvailableCapacity_eex_ex_post  \
DateTime   Fuel                      EICCode          Unit                     UnitID
2015-01-01 Biomass                   nan              BMHKW Piesteritz         E000114-001                          289.0
           Fossil Brown coal/Lignite 11WD2BUSD0000386 Buschhaus                E000119-001                          289.0
                                     11WD7AUEN5BFOFBM Fabrik Fortuna Nord      E000081-001                          289.0
                                     11WD7BOLL5BFRFBC Fabrik Frechen/Wachtberg E000082-001                          289.0
                                     11WD7BOLL5XBEFBQ Fabrik Berrenrath        E000080-001                          289.0
                                     11WD7FRIM2B--P-G Frimmersdorf P           E000005-012                          179.0
                                     11WD7FRIM2B--Q-D Frimmersdorf Q           E000005-013                         1060.0
                                     11WD7LIES5B-WRKC Goldenberg GoWerk        E000083-001                         1060.0
                                     11WD7NEUR1B--B-X Neurath B                E000077-002                         1060.0
                                     11WD7NEUR1B--C-U Neurath C                E000077-003                         1060.0
                                     11WD7NEUR1B--D-R Neurath D                E000077-004                         1060.0
                                     11WD7NEUR1B--E-O Neurath E                E000077-005                         1060.0
                                     11WD7NEUR1B--F-L Neurath F                E000077-006                         1060.0
                                     11WD7NEUR1B--G-I Neurath G                E000077-007                          750.0
                                     11WD7NEUR2B--A-T Neurath A                E000077-001                          500.0

                                                                                            AvailableCapacity_eex_real_time  \
DateTime   Fuel                      EICCode          Unit                     UnitID
2015-01-01 Biomass                   nan              BMHKW Piesteritz         E000114-001                            289.0
           Fossil Brown coal/Lignite 11WD2BUSD0000386 Buschhaus                E000119-001                            289.0
                                     11WD7AUEN5BFOFBM Fabrik Fortuna Nord      E000081-001                            289.0
                                     11WD7BOLL5BFRFBC Fabrik Frechen/Wachtberg E000082-001                            289.0
                                     11WD7BOLL5XBEFBQ Fabrik Berrenrath        E000080-001                            289.0
                                     11WD7FRIM2B--P-G Frimmersdorf P           E000005-012                            179.0
                                     11WD7FRIM2B--Q-D Frimmersdorf Q           E000005-013                           1060.0
                                     11WD7LIES5B-WRKC Goldenberg GoWerk        E000083-001                           1060.0
                                     11WD7NEUR1B--B-X Neurath B                E000077-002                           1060.0
                                     11WD7NEUR1B--C-U Neurath C                E000077-003                           1060.0
                                     11WD7NEUR1B--D-R Neurath D                E000077-004                           1060.0
                                     11WD7NEUR1B--E-O Neurath E                E000077-005                           1060.0
                                     11WD7NEUR1B--F-L Neurath F                E000077-006                           1060.0
                                     11WD7NEUR1B--G-I Neurath G                E000077-007                            750.0
                                     11WD7NEUR2B--A-T Neurath A                E000077-001                            500.0

                                                                                            AvailableCapacity_entsoe_ex_post  \
DateTime   Fuel                      EICCode          Unit                     UnitID
2015-01-01 Biomass                   nan              BMHKW Piesteritz         E000114-001                             289.0
           Fossil Brown coal/Lignite 11WD2BUSD0000386 Buschhaus                E000119-001                             289.0
                                     11WD7AUEN5BFOFBM Fabrik Fortuna Nord      E000081-001                             289.0
                                     11WD7BOLL5BFRFBC Fabrik Frechen/Wachtberg E000082-001                             289.0
                                     11WD7BOLL5XBEFBQ Fabrik Berrenrath        E000080-001                             289.0
                                     11WD7FRIM2B--P-G Frimmersdorf P           E000005-012                             179.0
                                     11WD7FRIM2B--Q-D Frimmersdorf Q           E000005-013                            1060.0
                                     11WD7LIES5B-WRKC Goldenberg GoWerk        E000083-001                            1060.0
                                     11WD7NEUR1B--B-X Neurath B                E000077-002                            1060.0
                                     11WD7NEUR1B--C-U Neurath C                E000077-003                            1060.0
                                     11WD7NEUR1B--D-R Neurath D                E000077-004                            1060.0
                                     11WD7NEUR1B--E-O Neurath E                E000077-005                            1060.0
                                     11WD7NEUR1B--F-L Neurath F                E000077-006                            1060.0
                                     11WD7NEUR1B--G-I Neurath G                E000077-007                             740.0
                                     11WD7NEUR2B--A-T Neurath A                E000077-001                             500.0

                                                                                            AvailableCapacity_entsoe_real_time  \
DateTime   Fuel                      EICCode          Unit                     UnitID
2015-01-01 Biomass                   nan              BMHKW Piesteritz         E000114-001                               289.0
           Fossil Brown coal/Lignite 11WD2BUSD0000386 Buschhaus                E000119-001                               289.0
                                     11WD7AUEN5BFOFBM Fabrik Fortuna Nord      E000081-001                               289.0
                                     11WD7BOLL5BFRFBC Fabrik Frechen/Wachtberg E000082-001                               289.0
                                     11WD7BOLL5XBEFBQ Fabrik Berrenrath        E000080-001                               289.0
                                     11WD7FRIM2B--P-G Frimmersdorf P           E000005-012                               289.0
                                     11WD7FRIM2B--Q-D Frimmersdorf Q           E000005-013                              1060.0
                                     11WD7LIES5B-WRKC Goldenberg GoWerk        E000083-001                              1060.0
                                     11WD7NEUR1B--B-X Neurath B                E000077-002                              1060.0
                                     11WD7NEUR1B--C-U Neurath C                E000077-003                              1060.0
                                     11WD7NEUR1B--D-R Neurath D                E000077-004                              1060.0
                                     11WD7NEUR1B--E-O Neurath E                E000077-005                              1060.0
                                     11WD7NEUR1B--F-L Neurath F                E000077-006                              1060.0
                                     11WD7NEUR1B--G-I Neurath G                E000077-007                              1060.0
                                     11WD7NEUR2B--A-T Neurath A                E000077-001                               500.0

                                                                                                                            Event_eex_ex_post  \
DateTime   Fuel                      EICCode          Unit                     UnitID
2015-01-01 Biomass                   nan              BMHKW Piesteritz         E000114-001                                                NaN
           Fossil Brown coal/Lignite 11WD2BUSD0000386 Buschhaus                E000119-001
                                     11WD7AUEN5BFOFBM Fabrik Fortuna Nord      E000081-001
                                     11WD7BOLL5BFRFBC Fabrik Frechen/Wachtberg E000082-001                          00000000000000#211573#953
                                     11WD7BOLL5XBEFBQ Fabrik Berrenrath        E000080-001
                                     11WD7FRIM2B--P-G Frimmersdorf P           E000005-012                          00000000000000#263872#896
                                     11WD7FRIM2B--Q-D Frimmersdorf Q           E000005-013                          00000000000000#263873#918
                                     11WD7LIES5B-WRKC Goldenberg GoWerk        E000083-001  00000000000000#176925#935;00000000000000#21171...
                                     11WD7NEUR1B--B-X Neurath B                E000077-002
                                     11WD7NEUR1B--C-U Neurath C                E000077-003
                                     11WD7NEUR1B--D-R Neurath D                E000077-004
                                     11WD7NEUR1B--E-O Neurath E                E000077-005
                                     11WD7NEUR1B--F-L Neurath F                E000077-006
                                     11WD7NEUR1B--G-I Neurath G                E000077-007  00000000000000#263940#920;00000000000000#26405...
                                     11WD7NEUR2B--A-T Neurath A                E000077-001

                                                                                                                          Event_eex_real_time  \
DateTime   Fuel                      EICCode          Unit                     UnitID
2015-01-01 Biomass                   nan              BMHKW Piesteritz         E000114-001
           Fossil Brown coal/Lignite 11WD2BUSD0000386 Buschhaus                E000119-001
                                     11WD7AUEN5BFOFBM Fabrik Fortuna Nord      E000081-001
                                     11WD7BOLL5BFRFBC Fabrik Frechen/Wachtberg E000082-001                          00000000000000#211573#953
                                     11WD7BOLL5XBEFBQ Fabrik Berrenrath        E000080-001
                                     11WD7FRIM2B--P-G Frimmersdorf P           E000005-012                          00000000000000#263872#896
                                     11WD7FRIM2B--Q-D Frimmersdorf Q           E000005-013                          00000000000000#263873#918
                                     11WD7LIES5B-WRKC Goldenberg GoWerk        E000083-001  00000000000000#176925#935;00000000000000#21171...
                                     11WD7NEUR1B--B-X Neurath B                E000077-002
                                     11WD7NEUR1B--C-U Neurath C                E000077-003
                                     11WD7NEUR1B--D-R Neurath D                E000077-004
                                     11WD7NEUR1B--E-O Neurath E                E000077-005
                                     11WD7NEUR1B--F-L Neurath F                E000077-006
                                     11WD7NEUR1B--G-I Neurath G                E000077-007  00000000000000#263940#920;00000000000000#26405...
                                     11WD7NEUR2B--A-T Neurath A                E000077-001

                                                                                              Event_entsoe_ex_post  \
DateTime   Fuel                      EICCode          Unit                     UnitID
2015-01-01 Biomass                   nan              BMHKW Piesteritz         E000114-001                     NaN
           Fossil Brown coal/Lignite 11WD2BUSD0000386 Buschhaus                E000119-001
                                     11WD7AUEN5BFOFBM Fabrik Fortuna Nord      E000081-001                     NaN
                                     11WD7BOLL5BFRFBC Fabrik Frechen/Wachtberg E000082-001
                                     11WD7BOLL5XBEFBQ Fabrik Berrenrath        E000080-001                     NaN
                                     11WD7FRIM2B--P-G Frimmersdorf P           E000005-012  R1NJMUNe4WZrVIV7q4rZCg
                                     11WD7FRIM2B--Q-D Frimmersdorf Q           E000005-013
                                     11WD7LIES5B-WRKC Goldenberg GoWerk        E000083-001                     NaN
                                     11WD7NEUR1B--B-X Neurath B                E000077-002
                                     11WD7NEUR1B--C-U Neurath C                E000077-003
                                     11WD7NEUR1B--D-R Neurath D                E000077-004
                                     11WD7NEUR1B--E-O Neurath E                E000077-005
                                     11WD7NEUR1B--F-L Neurath F                E000077-006
                                     11WD7NEUR1B--G-I Neurath G                E000077-007  Ph4xsgP_a7OoNQ6g_ripUg
                                     11WD7NEUR2B--A-T Neurath A                E000077-001

                                                                                           Event_entsoe_real_time  \
DateTime   Fuel                      EICCode          Unit                     UnitID
2015-01-01 Biomass                   nan              BMHKW Piesteritz         E000114-001                    NaN
           Fossil Brown coal/Lignite 11WD2BUSD0000386 Buschhaus                E000119-001
                                     11WD7AUEN5BFOFBM Fabrik Fortuna Nord      E000081-001                    NaN
                                     11WD7BOLL5BFRFBC Fabrik Frechen/Wachtberg E000082-001
                                     11WD7BOLL5XBEFBQ Fabrik Berrenrath        E000080-001                    NaN
                                     11WD7FRIM2B--P-G Frimmersdorf P           E000005-012
                                     11WD7FRIM2B--Q-D Frimmersdorf Q           E000005-013
                                     11WD7LIES5B-WRKC Goldenberg GoWerk        E000083-001
                                     11WD7NEUR1B--B-X Neurath B                E000077-002
                                     11WD7NEUR1B--C-U Neurath C                E000077-003
                                     11WD7NEUR1B--D-R Neurath D                E000077-004
                                     11WD7NEUR1B--E-O Neurath E                E000077-005
                                     11WD7NEUR1B--F-L Neurath F                E000077-006
                                     11WD7NEUR1B--G-I Neurath G                E000077-007
                                     11WD7NEUR2B--A-T Neurath A                E000077-001

                                                                                            InstalledCapacity  \
DateTime   Fuel                      EICCode          Unit                     UnitID
2015-01-01 Biomass                   nan              BMHKW Piesteritz         E000114-001              289.0
           Fossil Brown coal/Lignite 11WD2BUSD0000386 Buschhaus                E000119-001              289.0
                                     11WD7AUEN5BFOFBM Fabrik Fortuna Nord      E000081-001              289.0
                                     11WD7BOLL5BFRFBC Fabrik Frechen/Wachtberg E000082-001              289.0
                                     11WD7BOLL5XBEFBQ Fabrik Berrenrath        E000080-001              289.0
                                     11WD7FRIM2B--P-G Frimmersdorf P           E000005-012              289.0
                                     11WD7FRIM2B--Q-D Frimmersdorf Q           E000005-013             1060.0
                                     11WD7LIES5B-WRKC Goldenberg GoWerk        E000083-001             1060.0
                                     11WD7NEUR1B--B-X Neurath B                E000077-002             1060.0
                                     11WD7NEUR1B--C-U Neurath C                E000077-003             1060.0
                                     11WD7NEUR1B--D-R Neurath D                E000077-004             1060.0
                                     11WD7NEUR1B--E-O Neurath E                E000077-005             1060.0
                                     11WD7NEUR1B--F-L Neurath F                E000077-006             1060.0
                                     11WD7NEUR1B--G-I Neurath G                E000077-007             1060.0
                                     11WD7NEUR2B--A-T Neurath A                E000077-001              500.0

                                                                                            UnavailableCapacity_eex_ex_post  \
DateTime   Fuel                      EICCode          Unit                     UnitID
2015-01-01 Biomass                   nan              BMHKW Piesteritz         E000114-001                              0.0
           Fossil Brown coal/Lignite 11WD2BUSD0000386 Buschhaus                E000119-001                              0.0
                                     11WD7AUEN5BFOFBM Fabrik Fortuna Nord      E000081-001                              0.0
                                     11WD7BOLL5BFRFBC Fabrik Frechen/Wachtberg E000082-001                             45.0

In [12]:
df.info()

<class 'pandas.DataFrame'>
MultiIndex: 28080576 entries, (Timestamp('2015-01-01 00:00:00'), 'Biomass', nan, 'BMHKW Piesteritz', 'E000114-001') to (Timestamp('2024-12-31 23:00:00'), 'Wind Onshore', '14WDRX-WP-KW-TUK', 'UW Druxberge TU', 'E110500-001')
Data columns (total 12 columns):
 #   Column                              Dtype
---  ------                              -----
 0   ActualGenerationOutput              float64
 1   AvailableCapacity_eex_ex_post       float64
 2   AvailableCapacity_eex_real_time     float64
 3   AvailableCapacity_entsoe_ex_post    float64
 4   AvailableCapacity_entsoe_real_time  float64
 5   Event_eex_ex_post                   str
 6   Event_eex_real_time                 str
 7   Event_entsoe_ex_post                str
 8   Event_entsoe_real_time              str
 9   InstalledCapacity                   float64
 10  UnavailableCapacity_eex_ex_post     float64
 11  UnavailableCapacity_eex_real_time   float64
dtypes: float64(8), str(4)
memory usage: 3.3 GB

In [13]:
df.describe()

,ActualGenerationOutput,AvailableCapacity_eex_ex_post,AvailableCapacity_eex_real_time,AvailableCapacity_entsoe_ex_post,AvailableCapacity_entsoe_real_time,InstalledCapacity,UnavailableCapacity_eex_ex_post,UnavailableCapacity_eex_real_time
count,1.550676e+07,2.808058e+07,2.808058e+07,2.808058e+07,2.808058e+07,2.808058e+07,2.808058e+07,2.808058e+07
mean,1.695581e+02,2.818919e+02,2.814078e+02,2.847977e+02,3.102189e+02,3.340932e+02,5.145441e+01,5.210586e+01
std,2.896741e+02,3.111418e+02,3.113152e+02,3.109726e+02,3.131413e+02,3.118277e+02,1.528460e+02,1.530658e+02
min,-9.480000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.020000e+01,0.000000e+00,0.000000e+00
25%,0.000000e+00,1.080000e+02,1.070000e+02,1.080000e+02,1.130000e+02,1.160000e+02,0.000000e+00,0.000000e+00
50%,1.620000e+01,1.620000e+02,1.620000e+02,1.670000e+02,1.800000e+02,2.000000e+02,0.000000e+00,0.000000e+00
75%,2.082500e+02,3.520000e+02,3.520000e+02,3.530000e+02,4.250000e+02,4.500000e+02,0.000000e+00,0.000000e+00
max,1.510580e+03,1.410000e+03,1.410000e+03,1.410000e+03,1.410000e+03,1.410000e+03,1.410000e+03,1.410000e+03

In [14]:
print(df.columns.tolist())
print(df.index.names)

['ActualGenerationOutput', 'AvailableCapacity_eex_ex_post', 'AvailableCapacity_eex_real_time', 'AvailableCapacity_entsoe_ex_post', 'AvailableCapacity_entsoe_real_time', 'Event_eex_ex_post', 'Event_eex_real_time', 'Event_entsoe_ex_post', 'Event_entsoe_real_time', 'InstalledCapacity', 'UnavailableCapacity_eex_ex_post', 'UnavailableCapacity_eex_real_time']
['DateTime', 'Fuel', 'EICCode', 'Unit', 'UnitID']

In [15]:



FOLDER_PATH  = '../../UnavailabilityOfProductionAndGenerationUnits_15.1.A_B_C_D_r3'
OUTAGES_PATH = '../../outages_2015-2024.parquet'
SAVE_PATH    = '../data/outages_with_type.parquet'

DE_CODES = ['DE_LU', 'DE_Amprion', 'DE_TransnetBW', 'DE_TenneT_GER', 'DE_50HzT']

In [ ]:


outages = pd.read_parquet('../data/outages_2015-2024_clean.parquet')
print(f"Outages rows: {len(outages):,}")




type_map = (
    combined
    .groupby("InstanceCode")["Type"]
    .apply(lambda x: x.value_counts().index[0])
    .to_dict()
)
print(f"Unique event IDs in lookup: {len(type_map):,}")

STEP 3: Loading outages file...
Outages rows: 28,080,576

STEP 4: Building event ID → Type lookup...
Unique event IDs in lookup: 651,274

In [ ]:


event_col    = "Event_entsoe_ex_post"
clean_events = outages[event_col].dropna()
clean_events = clean_events[clean_events != ""]
all_ids      = clean_events.str.split(";").explode().str.strip().unique()
matches      = set(all_ids) & set(type_map.keys())

print(f"Event IDs in outages:  {len(all_ids):,}")
print(f"Event IDs in ENTSO-E:  {len(type_map):,}")
print(f"Matching:              {len(matches):,}  ({len(matches)/len(all_ids)*100:.1f}%)")

if len(matches) / len(all_ids) < 0.5:
    print("WARNING: less than 50% matched — check your files and column names")

STEP 5: Checking ID overlap...
Event IDs in outages:  60,501
Event IDs in ENTSO-E:  651,274
Matching:              56,474  (93.3%)

In [ ]:



def get_type(event_str):
    if pd.isna(event_str) or event_str == "":
        return ""
    ids     = [i.strip() for i in event_str.split(";")]
    types   = [type_map.get(i, "") for i in ids]
    types   = [t for t in types if t != ""]
    if not types:
        return ""
    planned = types.count("Planned")
    forced  = types.count("Forced")
    return "Planned" if planned > forced else "Unplanned"



print("\n Building Type column...")
outages["Type_entsoe_ex_post"] = outages[event_col].apply(get_type)
print(outages["Type_entsoe_ex_post"].value_counts())

STEP 7: Building Type column...
Type_entsoe_ex_post
             24181130
Planned       2959493
Unplanned      939953
Name: count, dtype: int64

In [ ]:


no_event  = outages[event_col].isna() | (outages[event_col] == "")
has_event = ~no_event
got_type  = outages["Type_entsoe_ex_post"] != ""

print(f"\nTotal rows:                    {len(outages):,}")
print(f"No event (unit available):     {no_event.sum():,}")
print(f"Has event:                     {has_event.sum():,}")
print(f"Has event + got type:          {(has_event & got_type).sum():,}  ← should be high")
print(f"Has event but no type:         {(has_event & ~got_type).sum():,}  ← should be low")

Total rows:                    28,080,576
No event (unit available):     24,018,882
Has event:                     4,061,694
Has event + got type:          3,899,446  ← should be high
Has event but no type:         162,248  ← should be low

In [ ]:
#understanding what are the untyped events (has event but no type) — are they mostly one fuel type? mostly early years?
untyped = outages[has_event & ~got_type]
print(untyped.index.get_level_values('Fuel').value_counts())
print(untyped.index.get_level_values('DateTime').year.value_counts().sort_index())

Fuel
Fossil Hard coal                   53748
Fossil Gas                         45553
Fossil Brown coal/Lignite          23260
Hydro Pumped Storage               21117
Nuclear                             8502
Fossil Coal-derived gas             7669
Other                               1720
Fossil Oil                           454
Hydro Water Reservoir                177
Hydro Run-of-river and poundage       48
Name: count, dtype: int64
DateTime
2015    35425
2016    11105
2017     2454
2018      251
2019        4
2021    96661
2022    11756
2023      722
2024     3870
Name: count, dtype: int64

In [ ]:
untyped_2021 = untyped[untyped.index.get_level_values('DateTime').year == 2021]
print(untyped_2021.index.get_level_values('Fuel').value_counts())

# check which specific event IDs are causing it
untyped_ids = (outages.loc[has_event & ~got_type, event_col]
               .str.split(';').explode().str.strip().unique())
print(f"\nUnique unmatched event IDs: {len(untyped_ids)}")

Fuel
Fossil Gas                         28658
Fossil Hard coal                   25350
Fossil Brown coal/Lignite          20946
Hydro Pumped Storage               15997
Fossil Coal-derived gas             3003
Nuclear                             1579
Other                                840
Hydro Water Reservoir                175
Fossil Oil                            65
Hydro Run-of-river and poundage       48
Name: count, dtype: int64

Unique unmatched event IDs: 3878

In [ ]:
outages.to_parquet(SAVE_PATH, index=True)
print(f"Saved to {SAVE_PATH}")

Saved to /Users/aditi/Documents/Hertie/Thesis/outages_with_type.parquet

In [ ]:
check = pd.read_parquet('../data/outages_with_type.parquet')
print(check.shape)
print(check['Type_entsoe_ex_post'].value_counts())
check.head()

(28080576, 13)
Type_entsoe_ex_post
             24181130
Planned       2959493
Unplanned      939953
Name: count, dtype: int64

                                                                                            ActualGenerationOutput  \
DateTime   Fuel                      EICCode          Unit                     UnitID
2015-01-01 Biomass                   nan              BMHKW Piesteritz         E000114-001                     NaN
           Fossil Brown coal/Lignite 11WD2BUSD0000386 Buschhaus                E000119-001                     NaN
                                     11WD7AUEN5BFOFBM Fabrik Fortuna Nord      E000081-001                     NaN
                                     11WD7BOLL5BFRFBC Fabrik Frechen/Wachtberg E000082-001                     NaN
                                     11WD7BOLL5XBEFBQ Fabrik Berrenrath        E000080-001                     NaN

                                                                                            AvailableCapacity_eex_ex_post  \
DateTime   Fuel                      EICCode          Unit                     UnitID
2015-01-01 Biomass                   nan              BMHKW Piesteritz         E000114-001                          289.0
           Fossil Brown coal/Lignite 11WD2BUSD0000386 Buschhaus                E000119-001                          289.0
                                     11WD7AUEN5BFOFBM Fabrik Fortuna Nord      E000081-001                          289.0
                                     11WD7BOLL5BFRFBC Fabrik Frechen/Wachtberg E000082-001                          289.0
                                     11WD7BOLL5XBEFBQ Fabrik Berrenrath        E000080-001                          289.0

                                                                                            AvailableCapacity_eex_real_time  \
DateTime   Fuel                      EICCode          Unit                     UnitID
2015-01-01 Biomass                   nan              BMHKW Piesteritz         E000114-001                            289.0
           Fossil Brown coal/Lignite 11WD2BUSD0000386 Buschhaus                E000119-001                            289.0
                                     11WD7AUEN5BFOFBM Fabrik Fortuna Nord      E000081-001                            289.0
                                     11WD7BOLL5BFRFBC Fabrik Frechen/Wachtberg E000082-001                            289.0
                                     11WD7BOLL5XBEFBQ Fabrik Berrenrath        E000080-001                            289.0

                                                                                            AvailableCapacity_entsoe_ex_post  \
DateTime   Fuel                      EICCode          Unit                     UnitID
2015-01-01 Biomass                   nan              BMHKW Piesteritz         E000114-001                             289.0
           Fossil Brown coal/Lignite 11WD2BUSD0000386 Buschhaus                E000119-001                             289.0
                                     11WD7AUEN5BFOFBM Fabrik Fortuna Nord      E000081-001                             289.0
                                     11WD7BOLL5BFRFBC Fabrik Frechen/Wachtberg E000082-001                             289.0
                                     11WD7BOLL5XBEFBQ Fabrik Berrenrath        E000080-001                             289.0

                                                                                            AvailableCapacity_entsoe_real_time  \
DateTime   Fuel                      EICCode          Unit                     UnitID
2015-01-01 Biomass                   nan              BMHKW Piesteritz         E000114-001                               289.0
           Fossil Brown coal/Lignite 11WD2BUSD0000386 Buschhaus                E000119-001                               289.0
                                     11WD7AUEN5BFOFBM Fabrik Fortuna Nord      E000081-001                               289.0
                                     11WD7BOLL5BFRFBC Fabrik Frechen/Wachtberg E000082-001                               289.0
                                     11WD7BOLL5XBEFBQ Fabrik Berrenrath        E000080-001                               289.0

                                                                                                    Event_eex_ex_post  \
DateTime   Fuel                      EICCode          Unit                     UnitID
2015-01-01 Biomass                   nan              BMHKW Piesteritz         E000114-001                        NaN
           Fossil Brown coal/Lignite 11WD2BUSD0000386 Buschhaus                E000119-001
                                     11WD7AUEN5BFOFBM Fabrik Fortuna Nord      E000081-001
                                     11WD7BOLL5BFRFBC Fabrik Frechen/Wachtberg E000082-001  00000000000000#211573#953
                                     11WD7BOLL5XBEFBQ Fabrik Berrenrath        E000080-001

                                                                                                  Event_eex_real_time  \
DateTime   Fuel                      EICCode          Unit                     UnitID
2015-01-01 Biomass                   nan              BMHKW Piesteritz         E000114-001
           Fossil Brown coal/Lignite 11WD2BUSD0000386 Buschhaus                E000119-001
                                     11WD7AUEN5BFOFBM Fabrik Fortuna Nord      E000081-001
                                     11WD7BOLL5BFRFBC Fabrik Frechen/Wachtberg E000082-001  00000000000000#211573#953
                                     11WD7BOLL5XBEFBQ Fabrik Berrenrath        E000080-001

                                                                                           Event_entsoe_ex_post  \
DateTime   Fuel                      EICCode          Unit                     UnitID
2015-01-01 Biomass                   nan              BMHKW Piesteritz         E000114-001                  NaN
           Fossil Brown coal/Lignite 11WD2BUSD0000386 Buschhaus                E000119-001
                                     11WD7AUEN5BFOFBM Fabrik Fortuna Nord      E000081-001                  NaN
                                     11WD7BOLL5BFRFBC Fabrik Frechen/Wachtberg E000082-001
                                     11WD7BOLL5XBEFBQ Fabrik Berrenrath        E000080-001                  NaN

                                                                                           Event_entsoe_real_time  \
DateTime   Fuel                      EICCode          Unit                     UnitID
2015-01-01 Biomass                   nan              BMHKW Piesteritz         E000114-001                    NaN
           Fossil Brown coal/Lignite 11WD2BUSD0000386 Buschhaus                E000119-001
                                     11WD7AUEN5BFOFBM Fabrik Fortuna Nord      E000081-001                    NaN
                                     11WD7BOLL5BFRFBC Fabrik Frechen/Wachtberg E000082-001
                                     11WD7BOLL5XBEFBQ Fabrik Berrenrath        E000080-001                    NaN

                                                                                            InstalledCapacity  \
DateTime   Fuel                      EICCode          Unit                     UnitID
2015-01-01 Biomass                   nan              BMHKW Piesteritz         E000114-001              289.0
           Fossil Brown coal/Lignite 11WD2BUSD0000386 Buschhaus                E000119-001              289.0
                                     11WD7AUEN5BFOFBM Fabrik Fortuna Nord      E000081-001              289.0
                                     11WD7BOLL5BFRFBC Fabrik Frechen/Wachtberg E000082-001              289.0
                                     11WD7BOLL5XBEFBQ Fabrik Berrenrath        E000080-001              289.0

                                                                                            UnavailableCapacity_eex_ex_post  \
DateTime   Fuel                      EICCode          Unit                     UnitID
2015-01-01 Biomass                   nan              BMHKW Piesteritz         E000114-001                              0.0
           Fossil Brown coal/Lignite 11WD2BUSD0000386 Buschhaus                E000119-001                              0.0
                                     11WD7AUEN5BFOFBM Fabrik Fortuna Nord      E000081-001                              0.0
                                     11WD7BOLL5BFRFBC Fabrik Frechen/Wachtberg E000082-001                             45.0
                                     11WD7BOLL5XBEFBQ Fabrik Berrenrath        E000080-001                              0.0

                                                                                            UnavailableCapacity_eex_real_time  \
DateTime   Fuel                      EICCode          Unit                     UnitID
2015-01-01 Biomass                   nan              BMHKW Piesteritz         E000114-001                                0.0
           Fossil Brown coal/Lignite 11WD2BUSD0000386 Buschhaus                E000119-001                                0.0
                                     11WD7AUEN5BFOFBM Fabrik Fortuna Nord      E000081-001                                0.0
                                     11WD7BOLL5BFRFBC Fabrik Frechen/Wachtberg E000082-001                               45.0
                                     11WD7BOLL5XBEFBQ Fabrik Berrenrath        E000080-001                                0.0

                                                                                           Type_entsoe_ex_post
DateTime   Fuel                      EICCode          Unit                     UnitID
2015-01-01 Biomass                   nan              BMHKW Piesteritz         E000114-001
           Fossil Brown coal/Lignite 11WD2BUSD0000386 Buschhaus                E000119-001
                                     11WD7AUEN5BFOFBM Fabrik Fortuna Nord      E000081-001
                                     11WD7BOLL5BFRFBC Fabrik Frechen/Wachtberg E000082-001
                                     11WD7BOLL5XBEFBQ Fabrik Berrenrath        E000080-001